---
layout: post
title: "A crazy bug!"
author: fabiand
---


A crazy bug!
============

00:42:05.764 *stdin*:0: libguestfs: error: bind: Address already in use

    â€¦

    <rwmjones> pino|work: ^^ that path is quite long
    <rwmjones> it's about 90+ chars
    <rwmjones> didn't you fix this recently?
    <pino> fabiand: 1.30.x, right?
    <pino> rwmjones: yes, i was checking when
    <fabiand> DEBUG util.py:399:   libguestfs-tools                  noarch 1:1.30.6-2.fc22         updates 135 k
    <fabiand> pino|work, ^^ yes
    <rwmjones> 55202a4d49a101392148d79cb2e1591428db2681 ?
    <pino> fabiand: workaround, set a shorter TMPDIR
    <pino> rwmjones: 79b2f19fe7ba1843146e89e2267f066ed6eeeb5b + 4 commits following
    <fabiand> how come that the length of the path name causes this error?
    <pino> the path for a unix socket is short
    <rwmjones> unix domain sockets are limited to 108 chars or something
    <fabiand> ahhh
    <fabiand> crazy
    <pino> char sun_path[] in struct sockaddr_un is a static buffer, usually 104 or 108 characters
    <fabiand> :)
    <fabiand> Those are so crazy bugs!
    <rwmjones> it has been fixed, but only upstream not in 1.30

::: {#footer}
[ May 12th, 2016 1:59pm ]{#timestamp}
:::
